package com.dynamoDbTest.demoDynamoDbTest.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "user")
@Builder
public class User {

    @DynamoDBHashKey(attributeName = "id") // attributeName ka optional
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBRangeKey
    @DynamoDBIndexHashKey(attributeName = "date", globalSecondaryIndexName = "data-index")
    private String date;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    private String email;
    @DynamoDBAttribute
    private String password;
}
